

[env]

# supports arbitrary env vars so mise can be used like direnv/dotenv
RUST_BACKTRACE=0
GO_ENV = 'GOLANG_MISE'
#COLORBT_SHOW_HIDDEN=1

MISE_USE_TOML= 1  #Set to 1 to default to using .mise.toml
MISE_VERBOSE=0  #This shows the installation output during rtx install and rtx plugin install.
MISE_LOG_FILE='./mise.log' #Output logs to a file.
MISE_LOG_FILE_LEVEL='debug' #This is useful if you want to store the logs but not have them litter your display.
MISE_DEBUG=0 #show DEBUG message in console
MISE_QUIET=1 #Equivalent to MISE_LOG_LEVEL=warn.
MISE_ERROR=1
MISE_TRACE=0


[tools]

golang = '1.22.1'

